# Generated by Django 4.2.1 on 2023-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название товара:')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото товара')),
                ('size', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('X', 'X'), ('XL', 'XL')], default='L', max_length=10, null=True, verbose_name='Размер этого товара:')),
                ('compound', models.CharField(blank=True, choices=[('Хлопок', 'Хлопок'), ('Синтетика', 'Синтетика'), ('Шерсть', 'Шерсть')], max_length=100, verbose_name='Состав:')),
                ('color', models.CharField(max_length=50, null=True, verbose_name='Цвет товара:')),
                ('made_in', models.CharField(blank=True, max_length=100, verbose_name='Где сделан это товар:')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара:')),
                ('shape', models.CharField(choices=[('Новая', 'Новая'), ('Б/У', 'Б/У')], max_length=100, verbose_name='Состояние товара:')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
